GET https://fullstackopen-gaxo.onrender.com/api/persons
###
GET https://fullstackopen-gaxo.onrender.com/
###
GET https://fullstackopen-gaxo.onrender.com/api/persons/2
###
GET https://fullstackopen-gaxo.onrender.com/api/persons/67
###
DELETE https://fullstackopen-gaxo.onrender.com/api/persons/1
###
POST https://fullstackopen-gaxo.onrender.com/api/persons HTTP/1.1
content-type: application/json

{
    "name": "John Marston",
    "number": "2301-2504"
}
###
POST https://fullstackopen-gaxo.onrender.com/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Idont Haveanumberson"
}
###
PUT https://fullstackopen-gaxo.onrender.com/api/persons/2 HTTP/1.1
content-type: application/json

{
    "name": "Ada Lovelace",
    "number": "9"
}
###
PUT http://localhost:3001/api/persons/2 HTTP/1.1
content-type: application/json

{
    "name": "Ada Lovelace",
    "number": "9"
}
###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/69ab27fc8736b2b3731da257
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/231223