GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/1
###
GET http://localhost:3001/api/persons/67
###
DELETE http://localhost:3001/api/persons/1
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "John Marston",
    "number": "2301-2504"
}
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Idont Haveanumberson"
}